
services:
  api:
    image: blockserver:latest
    container_name: blockserver
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    command: >
      uvicorn wsgi:app
      --host 0.0.0.0
      --port 8080
      --workers 2
